/******* Do not edit this file *******
 Simple Custom CSS and JS - by Silkypress.com
 Saved: Jun 25 2018 | 16:39:44 */

/* Add your JavaScript code here.

If you are using the jQuery library, then don't forget to wrap your code inside jQuery.ready() as follows:

jQuery(document).ready(function( $ ){
    // Your code in here
});

End of comment */
function hasAllKeys(keyList, object) {
    for (var index in keyList) {
        if (!object.hasOwnProperty(keyList[index])) {
            return false
        }
    }
    return true
}

//通用Request
function commonRequest(type, url, params, func) {
    params = params ? params : {};
    if (type.toUpperCase() != 'GET') {
        params = JSON.stringify(params)
    }
    var request = $.ajax({
        type: type,
        url: url,
        contentType: 'application/json',
        data: params,
        success: function (data) {
            func(data);
        },
        error: function (err) {
            func(err);
        }
    });
    return request
}


function urlParamsParse(str) {
    var params = {};
    var paramStr = str || window.location.search.slice(1);
    if (paramStr.length <= 0) {
        return params
    }
    paramStr.replace(/([^=&]+)=([^&]*)/g, function (m, key, value) {
        params[decodeURIComponent(key)] = decodeURIComponent(value);
    });
    return params;
}

function commonSubmitProposal(proposalData, func) {
    if (hasAllKeys(['name', 'phone', 'description'], proposalData)) {
        var subData = buildProposalData(proposalData);
        var url = '/projects/proposal/submit';
        commonRequest('POST', url, subData, func)
    } else {
        func({result: false, message: "姓名、联系方式、需求描述为必填"});
    }
}

function buildProposalData(proposalData) {
    var params = urlParamsParse();
    if (location.hash) {
        proposalData.code = location.hash.substr(1);
    }
    if (params.track_code) {
        proposalData.track_code = params.track_code;
    }
    proposalData.path = window.location.pathname;
    proposalData.href = window.location.href;
    var referer = $.cookie('gearSourceReferer');
    if (referer && proposalData.href != referer) {
        proposalData.recent_referer = referer
    }
    if (document.referrer) {
        if (document.referrer.indexOf("ad.toutiao") != -1) {
            proposalData.recent_referer = document.referrer;
            proposalData.source = "头条"
        } else if (document.referrer.indexOf("www.baidu.com") != -1) {
            proposalData.recent_referer = document.referrer;
            proposalData.source = "百度"
        }
    }
    return proposalData
}

var SubmitModal = {
    showModal: function () {
        $('.landing-submit-modal').show();
        $('.landing-submit-modal .form-modal').show();
        stopBodyScroll(true);
    },
    closeModal: function () {
        $('.landing-submit-modal .center-box').hide();
        $('.landing-submit-modal').hide();
        stopBodyScroll(false);
    },
    descriptionAreaInput: function (e) {
        if (e.target.value.length >= 5) {
            $(e.target).siblings('.form-description-message').hide();
            $(e.target).removeClass('form-warning');
        }
    },
    submitProposalForm: function (wrapId) {
        var subData = {};
        //姓名 手机号 描述 预算 公司名
        var filedList = ['name', 'phone', 'description', 'budget', 'company', 'project_category'];
        for (var i = 0; i < filedList.length; i++) {
            var filedName = filedList[i];
            var selector = "#{wrapId} [name='{filedName}']".replace('{wrapId}', wrapId).replace('{filedName}', filedName);
            if ($(selector).length > 0) {
                var fieldValue = $(selector).val() && ($(selector).val() instanceof Array)
                    ?
                    $(selector).val().join(',').trim()
                    :
                    $(selector).val().trim();
                // var fieldValue = value;
                if (filedName == 'description') {
                    console.log(filedName)
                    if (!fieldValue || fieldValue.length < 5) {
                        $(selector).siblings('.form-description-message').show();
                        $(selector).addClass('form-warning');
                        return
                    }
                }
                subData[filedName] = fieldValue
            }
        }
        for (var filedName in subData) {
            var fieldValue = subData[filedName];
            if (!fieldValue) {
                return
            }
        }
        $('#' + wrapId + ' .submit-ing-footer').show();
        for (var i = 0; i < filedList.length; i++) {
            var filedName = filedList[i];
            var selector = "#{wrapId} [name='{filedName}']".replace('{wrapId}', wrapId).replace('{filedName}', filedName);
            $(selector).val('')
        }
        this.submitProposalData(subData)
    },
    submitProposalData: function (proposalData) {
        var that = this;
        $('.landing-submit-modal .form-modal').hide();
        $('.landing-submit-modal .loading-modal').show();
        commonSubmitProposal(proposalData, function (data) {
            if (data.result) {
                $('.landing-submit-modal .loading-modal').hide();
                $('.landing-submit-modal .success-modal').show();
            } else {
                $('.landing-submit-modal .loading-modal').hide();
                $('.landing-submit-modal .err-modal').show();
            }
            setTimeout(function () {
                that.closeModal()
            }, 3600)
        });
    },
}

jQuery(document).ready(function ($) {
    var mainContent = $('#primary').height();
    var secondaryHeight = $('#secondary').height();
    var topMargin = $(window).scrollTop();
    var windowWidth = $(window).width();
    fixSilder(topMargin, windowWidth, secondaryHeight, mainContent);
    $(window).scroll(function (event) {
        var scrollTop = $(window).scrollTop();
        var w = $(window).width();
        fixSilder(scrollTop, w, secondaryHeight, mainContent);
    });
    $(window).resize(function (event) {
        var w = $(window).width();
        resizeMargin = $(window).scrollTop();
        fixSilder(resizeMargin, w, secondaryHeight, mainContent);
    });
});

//右侧栏固定
var fixSilder = function (scollTop, w, second, main) {
    if (w >= 1200) {
        if (scollTop > 450) {
            var rightPosition = (w - 1200) / 2 - 70;
            if (scollTop + second > main + 450) {
                //$('#secondary').css({'position': 'static'});
                //$('.blog-sub').css({'margin-top': main - 500});
            } else {
                //$('#secondary').css({'position': 'fixed', 'top': '0', 'right': rightPosition});
                //$('.blog-sub').css({'margin-top': 105});
            }
        } else {
            //$('#secondary').css({'position': 'static'});
        }

    } else {
        //$('#secondary').css({'position': 'static'});
    }
};

//header
/*****首页header背景*****/
var switchNavBg = function () {
    var w = $(window).width();
    var y = $(window).scrollTop();
    var isOpenToggleBtn = $('.navbar-toggle .icon-close-bar').hasClass('hidden')
    if (y > 1) {
        $('#top').removeClass('new-face').addClass('with-shadow');
    } else {
        if (isOpenToggleBtn) {
            $('#top:not(.no-banner)').addClass('new-face').removeClass('with-shadow');
        } else {
            $('#top').removeClass('new-face').addClass('with-shadow');
        }
    }
};
switchNavBg()
var pathName = window.location.pathname;
$('#headerNav a').each(function(index,item){
    var href = $(item).attr('href')
    if(href == pathName){
        $(item).addClass('nav-active');
    }
    if(/^(\/blog\/)/.test(href) && /^(\/blog\/)/.test(pathName)){
        $(item).addClass('nav-active');
    }
});
$('#header-solution a').each(function(index,item){
    if($(item).attr('href') == pathName){
        $('#header-solution-title').addClass('nav-active');
    }
});
$(document).ready(function () {
    $(window).scroll(function (event) {
        switchNavBg();
    });
    switchNavBg();
    $(window).resize(function (event) {
        switchNavBg();
    });
});
/*****首页header结束*****/
/******* Do not edit this file *******
 Simple Custom CSS and JS - by Silkypress.com
 Saved: Oct 15 2017 | 18:37:36 */
$(document).ready(function () {
    $(document.body).on('click', '.open-modal', function () {
        SubmitModal.showModal()
    });
//解决微信浏览器输入框顶部布局不会弹的问题
    $(document.body).on('blur', 'input,textarea,select', function () {
        setTimeout(function () {
            var scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0;
            window.scrollTo(0, Math.max(scrollHeight - 1, 0));
        }, 100)
    });
    setSourceReferer();
    $('.hangye-has-arrow').click(function () {
        $(this).toggleClass('hangye-open');
    });
    $('.navbar-toggle').click(function () {
        var y = $(window).scrollTop();
        $('.navbar-toggle .icon-bar').toggleClass('hidden');
        $('.navbar-toggle .icon-close-bar').toggleClass('hidden');
        if (y < 150) {
            $('.site-header').toggleClass('new-face');
        }
    });
});

function parseUrlParams(str) {
    var params = {};
    var paramStr = str || window.location.search.slice(1);
    if (paramStr.length <= 0) {
        return params
    }
    paramStr.replace(/([^=&]+)=([^&]*)/g, function (m, key, value) {
        params[decodeURIComponent(key)] = decodeURIComponent(value);
    });
    return params;
}

function setSourceReferer() {
    var params = parseUrlParams();
    if (params.hasOwnProperty('source')) {
        var referer = $.cookie('gearSourceReferer');
        if (!(params.source != 'baidu' && referer && referer.indexOf("source=baidu") != -1)) {
            $.cookie('gearSourceReferer', window.location.href, {expires: 1});
        }
    }
}

function isPhone() {
    var userAgentInfo = navigator.userAgent;
    var Agents = ["Android", "iPhone",
        "SymbianOS", "Windows Phone",
        "iPad", "iPod"];
    var flag = false;
    for (var v = 0; v < Agents.length; v++) {
        if (userAgentInfo.indexOf(Agents[v]) > 0) {
            flag = true;
            break;
        }
    }
    return flag

}

// 拨打电话
function callTal() {
    if (isPhone()) {
        window.location.href = "tel:400-668-3138";
    }
}

//是否允许body滚动
function stopBodyScroll(isFixed) {
    if (isFixed) {
        var scrollTop = document.body.scrollTop || document.documentElement.scrollTop;
        document.body.style.cssText
            +=
            'position:fixed;width:100%;top:-' + scrollTop + 'px;';
    } else {
        var body = document.body;
        body.style.position = 'static';
        var top = body.style.top;
        document.body.scrollTop = document.documentElement.scrollTop = -parseInt(top);
        body.style.top = '';
    }
}